
CREATE TABLE IF NOT EXISTS TEACHERS
(
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(64) NOT NULL
);

INSERT INTO TEACHERS (NAME) VALUES
('Ali'),
('Vali'),
('Bobur'),
('Nozima'),
('Shaxlo');



CREATE TABLE IF NOT EXISTS SUBJECTS
(
    ID SERIAL PRIMARY KEY,
    SUBJECT_NAME VARCHAR(64) NOT NULL,
    TEACHER_ID INT,
    CONSTRAINT FK_TEACHER_ID FOREIGN KEY (TEACHER_ID) REFERENCES TEACHERS(ID)
);

INSERT INTO SUBJECTS (SUBJECT_NAME, TEACHER_ID) VALUES
('Algebra', 1),
('Geometriya', 2),
('Fizika', 3),
('Rus tili', 4);



SELECT TEACHERS.NAME, COUNT(SUBJECTS.ID)
FROM TEACHERS LEFT JOIN SUBJECTS ON TEACHERS.ID = SUBJECTS.TEACHER_ID
GROUP BY TEACHERS.ID, TEACHERS.NAME;
