
CREATE TABLE IF NOT EXISTS EMPLOYEES
(
  ID SERIAL PRIMARY KEY,
  NAME VARCHAR(64) NOT NULL,
  DEPARTMENT_ID INT,
  CONSTRAINT FK_DEPARTMENT_ID FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENTS(ID)
);

INSERT INTO EMPLOYEES (NAME, DEPARTMENT_ID) VALUES
('Ali', 1),
('Vali', 2),
('Gani', NULL),
('Joni', 4);



CREATE TABLE IF NOT EXISTS DEPARTMENTS
(
    ID SERIAL PRIMARY KEY,
    DEPARTMENT_NAME VARCHAR(64) NOT NULL
);

INSERT INTO DEPARTMENTS (DEPARTMENT_NAME) VALUES
('Marketing'),
('Sales'),
('Finance'),
('Productions');



SELECT EMPLOYEES.NAME, DEPARTMENTS.DEPARTMENT_NAME
FROM EMPLOYEES LEFT JOIN DEPARTMENTS ON EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.ID
WHERE DEPARTMENTS.DEPARTMENT_NAME IS DISTINCT FROM 'Marketing';
