
CREATE TABLE IF NOT EXISTS AUTHORS
(
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(64) NOT NULL
);

INSERT INTO AUTHORS (NAME) VALUES
('Author1'),
('Author2'),
('Author3'),
('Author4'),
('Author5');



CREATE TABLE IF NOT EXISTS BOOKS
(
    ID SERIAL PRIMARY KEY,
    TITLE VARCHAR(64) NOT NULL,
    AUTHOR_ID INT,
    CONSTRAINT FK_AUTHOR_ID FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHORS(ID),
    PUBLISHED_YEAR DATE
);

INSERT INTO BOOKS (TITLE, AUTHOR_ID, PUBLISHED_YEAR) VALUES
('Title1', 1, '2025-07-07'),
('Title2', 2, '2025-08-08'),
('Title3', 3, '2025-09-09'),
('Title4', 4, '2025-10-10');



SELECT AUTHORS.NAME, COUNT(BOOKS.ID)
FROM AUTHORS LEFT JOIN BOOKS ON AUTHORS.ID = BOOKS.AUTHOR_ID
GROUP BY AUTHORS.ID, AUTHORS.NAME;
