
CREATE TABLE IF NOT EXISTS customers
(
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(64) NOT NULL
);

INSERT INTO customers (NAME) VALUES
('Ali'),
('Vali'),
('Gani'),
('Ali');



CREATE TABLE IF NOT EXISTS orders
(
    ID SERIAL PRIMARY KEY,
    CUSTOMER_ID INT,
    CONSTRAINT FK_CUSTOMER_ID FOREIGN KEY (CUSTOMER_ID) REFERENCES customers(ID),
    ORDER_DATE DATE,
    TOTAL_AMOUNT INT NOT NULL
);

INSERT INTO orders (CUSTOMER_ID, ORDER_DATE, TOTAL_AMOUNT) VALUES
(1, '2024-01-01', 10),
(2, '2024-03-11', 15),
(3, '2025-12-10', 17),
(1, '2024-02-10', 27);



SELECT customers.NAME, COUNT(orders.ID) AS total_orders
FROM customers INNER JOIN orders ON customers.ID = orders.CUSTOMER_ID
WHERE ORDER_DATE BETWEEN '2024-01-01' AND '2024-12-31'
GROUP BY customers.name;
