
CREATE TABLE IF NOT EXISTS DRIVERS
(
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(64) NOT NULL
);

INSERT INTO DRIVERS (NAME) VALUES
('Driver1'),
('Driver2'),
('Driver3'),
('Driver4');



CREATE TABLE IF NOT EXISTS TRIPS
(
    ID SERIAL PRIMARY KEY,
    DRIVER_ID INT,
    CONSTRAINT FK_DRIVER_ID FOREIGN KEY (DRIVER_ID) REFERENCES DRIVERS(ID),
    TRIP_DATE DATE,
    DISTANCE INT NOT NULL
);

INSERT INTO TRIPS (DRIVER_ID, TRIP_DATE, DISTANCE) VALUES
(1, '2025-01-01', 3000),
(2, '2025-01-11', 4000),
(3, '2025-02-09', 3500);



SELECT DRIVERS.NAME, SUM(TRIPS.DISTANCE)
FROM DRIVERS INNER JOIN TRIPS ON DRIVERS.ID = TRIPS.DRIVER_ID
WHERE TRIPS.TRIP_DATE BETWEEN '2025-01-01' AND '2025-01-31'
GROUP BY DRIVERS.ID, DRIVERS.NAME;
