
CREATE TABLE IF NOT EXISTS USERS
(
    ID SERIAL PRIMARY KEY,
    FULLNAME VARCHAR(128) NOT NULL,
    ADDRESS VARCHAR(128) NOT NULL,
    MOBILE_PHONE CHAR(13) NOT NULL
);

INSERT INTO USERS (FULLNAME, ADDRESS, MOBILE_PHONE) VALUES
('User1', 'Address1', '+998991112233'),
('User2', 'Address2', '+998991112244'),
('User3', 'Address3', '+998991112255'),
('User4', 'Address4', '+998991112266');



CREATE TABLE IF NOT EXISTS PRODUCTS
(
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(64) NOT NULL,
    PRICE INT NOT NULL,
    DISCOUNT VARCHAR(32) NOT NULL
);

INSERT INTO PRODUCTS (NAME, PRICE, DISCOUNT) VALUES
('Product1', 20000, '20%'),
('Product1', 20000, '20%'),
('Product1', 20000, '20%'),
('Product1', 20000, '20%');



CREATE TABLE IF NOT EXISTS ORDERS
(
    ID SERIAL PRIMARY KEY,
    USER_ID INT,
    CONSTRAINT FK_USER_ID FOREIGN KEY (USER_ID) REFERENCES USERS(ID),
    PRODUCT_ID INT,
    CONSTRAINT FK_PRODUCT_ID FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(ID),
    COUNT INT NOT NULL,
    STATUS status_type
);
--  PSQLda create_status qilib oldim

INSERT INTO ORDERS (USER_ID, PRODUCT_ID, COUNT, STATUS) VALUES
(1, 1, 2, 'pending'),
(2, 2, 1, 'pending'),
(3, 3, 5, 'completed'),
(4, 4, 3, 'completed');



